    - name: Build Debug APK
      env:
        VERSION_CODE: "1"
        VERSION_NAME: "1.0.0"
        BRANCH_NAME: "main"
      run: |
        ./gradlew assembleUnstableDebug \
          -DVERSION_CODE=1 \
          -DVERSION_NAME=1.0.0 \
          -PKEYSTORE_FILE="$GITHUB_WORKSPACE/dummy.keystore" \
          -PKEYSTORE_PASSWORD="123456" \
          -PKEY_ALIAS="dummy" \
          -PKEY_PASSWORD="123456" \
          --stacktrace \
          --no-daemon
